### ISSUE TITLE
Leapchat certificate failure

### ISSUE THREAD

**Issue by JimiHendricks** [cryptag/leapchat#227] opened 2022-02-01 03:08 UTC
Leapchat is failing on Apple devices - shows cert revoked. Most Windows devices currently working.

**Comment by adana-github** [comment] 2022-02-01 04:51
Firefox on windows gives:

An error occurred during a connection to www.leapchat.org. Peer’s Certificate has been revoked.

Error code: SEC_ERROR_REVOKED_CERTIFICATE

**Comment by adana-github** [comment] 2022-02-01 04:51
Still works on opera and chrome

**Comment by elimisteve** [comment] 2022-02-01 09:56
Very strange, thanks for the reports! My monitoring service didn't catch it for some reason. May be LetsEncrypt-related... I think LeapChat may still use an old LetsEncrypt endpoint that's going away.

Thanks for the report, @JimiHendricks and @adana-github!

**Comment by elimisteve** [comment] 2022-02-01 11:03
@JimiHendricks @adana-github LeapChat should now be up for all devices! I checked in Firefox, and the SSL issue that I saw when you helpfully reported the problem is now gone. Thanks!

**Closed as completed by elimisteve** 2022-02-01 11:03 UTC

**Comment by adana-github** [comment] 2022-02-01 15:11
Thank you!

-Abe
